.github/pull_request_template.md, .prettierignore
create pull request template
it should contain only two sections:
- description
- ticket url
=> chore: create pull request template

package.json, src/index.ts, yarn.lock
Connect with MongoDB Atlas Database.
https://sharing.clickup.com/26492745/t/h/340y83w/1569E9JWXYIAQH4
=> build: connect with database

package.json, yarn.lock
Added dependencies for web scrapers and scheduler.
https://app.clickup.com/t/862hxzyng
=> Build: add dependencies for web scrapers

package.json, yarn.lock
Add jsonwebtoken, bcrypt, cors, cookie-parser and body-parser to dependencies
https://sharing.clickup.com/26492745/t/h/862hycjq7/HFK6Z443Z6T17RS
=> build: add dependencies

src/Models/users.model.ts, src/Types/Users.ts
Create model and type for users collection 
https://sharing.clickup.com/26492745/t/h/862hycjyk/HFK6Z443Z6T17RS
=> feat: create user model

.github/workflows/CI.yml, jest.config.js, src/Configs/db.config.ts, src/Services/login.service.ts, src/index.ts, tests/Services/login.service.test.ts
Fix jest config and create tests for admin login service
https://sharing.clickup.com/26492745/t/h/862hyckfa/HFK6Z443Z6T17RS
=> test: test login service

.github/workflows/CI.yml, jest.config.js, src/Configs/db.config.ts, src/Models/users.model.ts, src/Services/login.service.ts, src/Types/User.ts, src/index.ts, tests/Services/login.service.test.ts
Create service for login feature
https://sharing.clickup.com/26492745/t/h/862hyckfa/HFK6Z443Z6T17RS
=> Feat: create login service

.github/workflows/CI.yml, src/Controllers/login.controller.ts, tests/Controllers/login.controller.test.ts, tests/Services/login.service.test.ts, tests/add.test.ts
Create tests for login controller
https://sharing.clickup.com/26492745/t/h/862hyckyx/HFK6Z443Z6T17RS
=> test: test login controller

package.json, src/Routes/login.route.ts, src/index.ts, tests/Controllers/login.controller.test.ts, tests/Routes/login.route.test.ts, tests/Services/login.service.test.ts, tests/utils/mockResponse.ts, yarn.lock
Create route for login feature
https://sharing.clickup.com/26492745/t/h/862hycm6x/HFK6Z443Z6T17RS
=> feat: create login route

src/Services/majorsScraper.service.ts, src/utils/majorsScraper/fixMajorName.spec.ts, src/utils/majorsScraper/fixMajorName.ts
now majors scraper returns 'Tryb stacjonarny' which needs to be removed from other majors
https://app.clickup.com/t/862j3x87p
=> fix: fix majors scraper

src/Controllers/majors.controller.ts, src/Models/majors.model.ts, src/Routes/majors.route.ts, src/Schedulers/majors.scheduler.ts, src/Services/majorsScraper.service.ts, src/index.ts
set up cron job for majors web scraper, all the majors in database need to be wiped out and replaced by new data coming from web scraper every day at midnight
add two endpoints:
- GET '/majors' to get all the majors
- GET '/majors/<id>' to get a specific major
https://app.clickup.com/t/862j3x889
=> feat: add majors to db

.dockerignore, .github/workflows/CI.yml, Dockerfile, docker-compose.yml, entrypoint.sh, package.json
Fix docker-compose so it will be possible to develop and run tests using Docker containers and create Dockerfile which will be used for deployment of our app.
https://sharing.clickup.com/26492745/t/h/862j8wezw/CWQJG3AWBMQOIT4
=> chore: fix docker

Dockerfile, docker-compose.yml, src/Configs/db.config.ts
Configure hosting of app on Render. It should be updated on every push to `main`  branch
https://sharing.clickup.com/26492745/t/h/862jcv1vw/YAREFET3NJCZ9ON
=> feat: host app on Render

README.md, docs/CONTRIBUTING.md
Create README and contribution guide for the repository
https://sharing.clickup.com/26492745/t/h/340y7zw/8PS6FIOA98055BA
=> docs: provide basic documentation

docker-compose.yml
Fix docker-compose.yml file
https://sharing.clickup.com/26492745/t/h/862jg7cjc/CFDPJSN4RLR49W6
=> fix: fix docker-compose

.gitignore, .metals/metals.lock.db, src/Controllers/news.controller.ts, src/Models/news.model.ts, src/Routes/news.route.ts, src/Schedulers/news.scheduler.ts, src/Services/lessonsPlansScrapper.service.ts, src/Services/majorsScraper.service.ts, src/Services/newsScraper.service.ts, src/Services/staffScraper.service.ts, src/Types/News.type.ts, src/app.ts, src/index.ts, src/utils/errorScraper.spec.ts, src/utils/errorScraper.ts, src/utils/newsScraper/fixDate.spec.ts, src/utils/newsScraper/fixDate.ts, src/utils/newsScraper/removeSeeMore.spec.ts, src/utils/newsScraper/removeSeeMore.ts, src/utils/newsScraper/returnCategoryEnum.spec.ts, src/utils/newsScraper/returnCategoryEnum.ts, src/utils/newsScraper/splitByLines.spec.ts, src/utils/newsScraper/splitByLines.ts
Create a web scraper for news. It should get news from https://inf.ug.edu.pl/news, https://inf.ug.edu.pl/studinfo and https://mfi.ug.edu.pl/wydzial/aktualnosci, https://mfi.ug.edu.pl/wydzial/aktualnosci/archiwum-aktualnosci. It should get info including title, short and long description, date, photo and site.
https://app.clickup.com/t/38g19hz
=> Feat: create news scraper

src/Schedulers/lessonsPlans.scheduler.ts, src/Services/lessonsPlansScrapper.service.ts, src/Types/lessonsPlanURLObject.type.ts
Change mapping of groups so there are no 'all' groups but a list of all possible groups
https://sharing.clickup.com/26492745/t/h/862j3vzjt/9NLFF395NAPKHNB
=> feat: refactor lessons plans webscrapper

src/Controllers/news.controller.ts, src/Models/news.model.ts, src/Services/newsScraper.service.ts, src/Types/News.type.ts, src/utils/newsScraper/convertStringToDate.spec.ts, src/utils/newsScraper/convertStringToDate.ts
Added searching by source, changed string to date format and fixed some bugs.
https://app.clickup.com/t/862jmurkf
=> feat: news improvements

src/Schedulers/news.scheduler.ts
Remove news duplicates from database
=> fix: remove news duplicates

src/Models/news.model.ts, src/Services/newsScraper.service.ts, src/Types/News.type.ts
Load all photos from news page.
=> feat: news many photos
